
insert into ES_PORTFOLIO (ID_PORTFOLIO, NAME_PORTFOLIO)
values(1, 'PORT-01');
insert into ES_PORTFOLIO (ID_PORTFOLIO, NAME_PORTFOLIO)
values(2, 'PORT-02');



insert into ES_FINASSET (ID_FINASSET, NAME_FINASSET, ID_PORTFOLIO_FINASSET)
values(1, 'ASSET-01', 1);
insert into ES_FINASSET (ID_FINASSET, NAME_FINASSET, ID_PORTFOLIO_FINASSET)
values(2, 'ASSET-02', 1);
insert into ES_FINASSET (ID_FINASSET, NAME_FINASSET, ID_PORTFOLIO_FINASSET)
values(3, 'ASSET-03', 2);
insert into ES_FINASSET (ID_FINASSET, NAME_FINASSET, ID_PORTFOLIO_FINASSET)
values(4, 'ASSET-04', 2);


