
-- h2 Database


DROP TABLE IF EXISTS ES_PORTFOLIO;

create table ES_PORTFOLIO (
   ID_PORTFOLIO BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME_PORTFOLIO varchar(100) NOT NULL
);



DROP TABLE IF EXISTS ES_FINASSET;

create table ES_FINASSET (
   ID_FINASSET BIGINT AUTO_INCREMENT PRIMARY KEY,
   ID_PORTFOLIO_FINASSET BIGINT,
   NAME_FINASSET varchar(100) NOT NULL,
   --PRICE_FINASSET NUMBER(6),
   --DATE_CREATION_FINASSET DATE,
	
   -- FOREIGN KEY definition is optional for hibernate mapping;
   FOREIGN KEY (ID_PORTFOLIO_FINASSET) REFERENCES ES_PORTFOLIO (ID_PORTFOLIO)
);

--COMMENT ON COLUMN ES_FINASSET.ID_FINASSET IS 'Preferred way to contact with employee';


-- drop table ES_FINASSET;
-- select * from ES_FINASSET;

